"""create user balance2

Revision ID: 8f26d3fffb83
Revises: 250a299a794e
Create Date: 2026-01-06 17:19:09.969920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f26d3fffb83'
down_revision: Union[str, Sequence[str], None] = '250a299a794e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Balance', ['sid'])
    op.create_unique_constraint(None, 'user', ['sid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'Balance', type_='unique')
    # ### end Alembic commands ###
